spring:
  datasource:
    url: jdbc:postgresql://192.168.0.176:5432/product_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: product-service
server:
  port: 8081
