name: Docker Image CI  # Workflow name

on:
  push:
    branches: ["main"]  # Trigger on pushes to main branch
  pull_request:
    branches: ["main"]  # Trigger on PRs targeting main branch

jobs:
  build-order-service:  # Job name 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Required for all jobs

    - name: Build Docker image
      working-directory: ./order-service  # Order service directory
      run: |
        docker build -t order-services:v1-${{ github.sha }} .  # Unique tag with commit SHA

  build-product-service:  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository  # checkout repo
      uses: actions/checkout@v4

    - name: Build Docker image
      working-directory: ./product-service  # Product service directory
      run: |
        docker build -t product-services:v1-${{ github.sha }} .  # build  & Unique versioned tag

  build-user-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository  # checkout repo
      uses: actions/checkout@v4

    - name: Build Docker image
      working-directory: ./user-service  # User service directory
      run: |
        docker build -t user-services:v1-${{ github.sha }} .  # building and versioned tag
